module.exports = {
  main_screen: {
    marginTop: 30,
    backgroundColor: "white",
    alignItems: "center",
    width: "100%",
    height: "90%",
  },
  main_screen_display: {
    elevation: 10,
    width: "95%",
    backgroundColor: "white",
    borderRadius: 10,
    marginBottom: 10,
    padding: 10,
  },
  display_text: {
    fontSize: 50,
    textAlign: "right",
  },
  keypad: {
    width: "100%",
    height: "70%",
  },
  keypad_row: {
    flexDirection: "row",
    backgroundColor: "white",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 10,
  },
  btn_outer: {
    width: 80,
    height: 80,
    backgroundColor: "white",
    elevation: 4,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
  },
  bg_button: {
    backgroundColor: "white",
    color: "black",
    fontSize: 30,
  },
  btn1_outer: {
    width: 80,
    height: 80,
    backgroundColor: "#F7AB0A",
    borderRadius: 90,
    elevation: 4,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  bg1_button: {
    color: "white",
    fontSize: 30,
    fontWeight: "bold",
  },
  btn2_outer: {
    width: 80,
    height: 80,
    backgroundColor: "gray",
    borderRadius: 10,
    elevation: 4,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  bg2_button: {
    color: "white",
    fontSize: 30,
    fontWeight: "bold",
  },
}
